version: 2
updates:
- package-ecosystem: bundler
  directory: "/common"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - greysteil
- package-ecosystem: pip
  directory: "/python/helpers"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/composer/helpers"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: mix
  directory: "/hex/helpers"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/npm_and_yarn/helpers"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
